# Generated by Django 4.0.4 on 2022-06-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True,
                                      serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='component',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True,
                                      serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='system',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True,
                                      serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True,
                                      serialize=False, verbose_name='ID'),
        ),
    ]
